FROM python:3.10-slim

WORKDIR /app

COPY airport-monitor-server/ /app/

# Install dependencies
RUN pip install --no-cache-dir -e .

ENV REDIS_HOST=redis
ENV REDIS_PORT=6379

ENTRYPOINT ["python", "server.py"]
CMD ["--http-port", "5001"]
